### PR TITLE
Pydantic v2

### PR DESCRIPTION
**Pull request by ollz272**
Bumps to pydantic v2. Please advise on any other updates needed, as we would like to start using v2 in our projects. thanks.

### CODE REVIEW

**Comment by yuval9313** [comment]
Hey, consider other people using this library and straighten with fastapi's approach on this subject

Since fastapi 0.100 supports pydantic v1 and v2 we should as well

**Comment by ollz272** [comment]
@yuval9313 Ok - I've updated the PR to support both v1 and v2. I've added into the test suite to test both v1 and v2 installs. I've also tested locally and looks okay to me.

**Comment by yuval9313** [comment]
Alright, I assume it's OK

Just one question, why didn't you include v2 in all? Also I assume default behavior should use pydantic 2, is there a way to not install dependencies when we want the v1? Does that makes sense?

Maybe it means that pydantic-settings should be installed for both v1 and v2?

What do you think?

**Comment by yuval9313** [comment]
Alright, I assume it's OK

Just one question, why didn't you include v2 in all? Also I assume default behavior should use pydantic 2, is there a way to not install dependencies when we want the v1? Does that makes sense?

Maybe it means that pydantic-settings should be installed for both v1 and v2?

What do you think?

**Comment by ollz272** [comment]
>why didn't you include v2 in all? 

I kinda assumed we'd want v2 to be explicitly optin - i can move this though

>  Also I assume default behavior should use pydantic 2, is there a way to not install dependencies when we want the v1?

I'm honestly not sure - i can take a look?

> Maybe it means that pydantic-settings should be installed for both v1 and v2?

pydantic-settings requires V2, so can only be installed when v2 is present.

**Comment by yuval9313** [comment]
I think the default option should be v2.
We want to progress and eventually rid of v1 when it is obsolete in fastapi 

I wish I could ask you to separate pydantic from this lib exactly like fastapi but unfortunately I'd call that out of scope

Can you please find out if it possible to install v1 via extras?

**Comment by yuval9313** [comment]
I know it's confusing but don't change the PR yet

Tell me if you think there is a solution to the v2/v1 issue prior to changing the lib

**Review by yuval9313 — APPROVED** [review]

**Comment by yuval9313** [comment]
Hey can you make sure you pass the ci?
We've decided that only braking change would replace the default version of pydantic

**Comment by ollz272** [comment]
> Hey can you make sure you pass the ci? We've decided that only braking change would replace the version of pydantic to v2

Thanks - I've updated:
- I've made the decision to only use mypy for V2. Its impossible to get it passing for both, and since this is default i figure this is the one worth type checking.
- I've updated the dependencies to install V2 things with all.

**Comment by ollz272** [comment]
Right @yuval9313 , sorry, that should *now* pass ci 😆

**Review by yuval9313 — APPROVED** [review]

**Comment by ollz272** [comment]
Thanks for approving @yuval9313! is it possible to get a release with this in soon? 🙏🏻

**Comment by yuval9313** [comment]
Yes, can you merge?

**Comment by ollz272** [comment]
@yuval9313 I dont have write permissions so can't merge, unfortunately.

**Pull request merged**
