### PR TITLE
Add proper __version__

### PR DESCRIPTION
**Pull request by pavelzw**

### CODE REVIEW

**Review by yuval9313 — APPROVED** [review]

**Comment by yuval9313** [comment]
Please open issue

**Comment by pavelzw** [comment]
Fixes #215

**Comment by pavelzw** [comment]
`importlib.metadata` is not available for python 3.7.
We either kick support for py3.7 since it is at end of life either way or I do a conditional import and use `pkg_resources` for python 3.7. 

What do you prefer @yuval9313?

**Comment by yuval9313** [comment]
We should confirm to @tiangolo's fastapi since these are additional tools to support with the construction of application using fastapi, so as long as they support 3.7 so do we unfortunately 


Tho I see as I write it that you found somewhat of a solution to the issue

**Review by yuval9313 — DISMISSED** [review]

**Review by yuval9313 — APPROVED** [review]

**Pull request merged**
