### PR TITLE
Fix routing problem

### PR DESCRIPTION
**Pull request by yen3**
Original issue: https://github.com/dmontagu/fastapi-utils/issues/154

Credit: WouldYouKindly <https://github.com/WouldYouKindly>

If we use class-based routing, the cbv causes the double routes.
WouldYouKindly solves the problem, but he does not the patch to the
repo. I really need the patch for my daily development so I copy his
solution to resolve.

If it causes anyone feels uncomfortable, I will delete my PR.

Sorry for the copy

### CODE REVIEW

**Comment by yairsimantov20** [comment]
is there any update for that pr?
would love to use that fix

**Comment by tnte** [comment]
Looking forward to this PR being accepted. Having the same issue.

**Comment by yuval9313** [comment]
It doesn't passes tests, so I first need to figure whats going on there,
If everything is fine i'll update

**Comment by zon7** [comment]
I think the first test failing should be /items? instead of /items/?

**Comment by JonathanWoodell** [comment]
Any new on getting these tests fixed.

**Comment by JonathanWoodell** [comment]
Any news on getting these tests fixed?

**Comment by Caindrac** [comment]
Any news on getting these tests fixed?

**Comment by yuval9313** [comment]
I was lacking the update, The new code create an issue where @router.get as decorator doesn't works which means:
1. The code was not forked properly
2. The new changes breaks this functionality
I can try to fix the fork so it won't drop the multiple routes functionality but I'm lacking the time so I don't know how much time it is going to take, anyway I'm starting it now

**Pull request merged**
